WINDOW_WIDTH = 460
WINDOW_HEIGHT = 720
WINDOW_CAPTION = "BREAKOUT"

SCREEN_DIMENSION = (WINDOW_WIDTH, WINDOW_HEIGHT)

PLAYER_PADDLE_IMG_PATH = "assets/white_player.png"
BOUNCE_SFX_PATH = 'assets/bounce.wav'
BGM_PATH = "assets/cheetahmen.wav"
